### ISSUE TITLE
Basic Resque Example?

### ISSUE THREAD

**Issue by tibbon** [jrgifford/delayed_paperclip#12]
I've got Resque running with a worker running, which I know is working as its also processing some Solr stuff in the background. 

In my document model I have the following:

```
  has_attached_file :upload, 
                :styles => { :preview => ["725x1200>", :jpg], :thumb => ["200x280>", :jpg] },
                :processors => [:ghostscript, :thumbnail],
                :convert_options => { :all => '-colorspace RGB -flatten -density 300 -quality 100' }

  process_in_background :upload
```

Yet, in the console it would appear that all of the image process stuff is happening on my web unicorn worker, not my resque_worker. Below is my Procfile.  

```
web: bundle exec unicorn -c lib/unicorn/config.rb -p $PORT
resque_worker: env QUEUE=* bundle exec rake environment resque:work
```

I'm sure I'm missing something terribly basic here, but what am I doing wrong?

**Comment by billy-ran-away** [comment]
I know this issue was closed over a year ago, however I'm having the same issue on Rails 4. Any advice?

**Comment by rianrainey** [comment]
I'm also having the same experience as @billy-ran-away. I'm using Rails 4, Resque 1.22 and Paperclip 4.2.1.

**Comment by rob-murray** [comment]
Have you guys tried setting Active Job queue adapter to Resque (or alternative) ?

I'm using Rails 4.2 and Sidekiq but had not set the config below so Active Job was just processing images synchronously. See [rails guides](http://edgeguides.rubyonrails.org/active_job_basics.html#backends).

```
# config/application.rb

# ...
config.active_job.queue_adapter = :sidekiq
```
