### ISSUE TITLE
Timestamps are being escaped when used with Paperclip 4.2.1

### ISSUE THREAD

**Issue by maxim** [jrgifford/delayed_paperclip#126]
The part right here:
https://github.com/jrgifford/delayed_paperclip/blob/master/lib/delayed_paperclip/url_generator.rb#L14-L18

Was fixed in Paperclip here: https://github.com/thoughtbot/paperclip/commit/ecfb5e2ac3257146cc3fd57ba63f52db1dff343a

But it gets monkeypatched by delayed_paperclip.

**Comment by ScotterC** [comment]
Thanks @maxim!  Any chance you could PR that over?

**Comment by maxim** [comment]
@ScotterC Perhaps we should get rid of `alias_method_chain`, instead use inheritance to write our own `UrlGenerator` based on paperclip's. Maybe I'll try that as a less coupled way of integrating with paperclip, let's see how that'd look.

**Comment by maxim** [comment]
@ScotterC oh just noticed it's a module, nevermind, will look more into it

**Comment by maxim** [comment]
I added an unfinished pull request, explanation there https://github.com/jrgifford/delayed_paperclip/pull/127

**Comment by ScotterC** [comment]
:+1:   Thanks @maxim

**Comment by consti** [comment]
Thanks for looking into that @maxim - I'm running into the same issue and hope there'll be a working fix, soonish. Let me know if you need any help!

**Comment by ScotterC** [comment]
We'll let you know @consti!  @maxim and I spent half of this past Sunday untangling the UrlGenerator.  Hoping to have a revamped, cleaner piece of code soon

**Comment by roymckenzie** [comment]
@maxim and @ScotterC, is this open issue related to why I am seeing:

`imagename.jpg%3F1421493843` instead of `imagename.jpg?1421493843` and my images are broken?

If it is not related I can open up a new issue.

Thank you for actively maintaining this gem! I'm looking forward to using it!

**Comment by consti** [comment]
>
> imagename.jpg%3F1421493843 instead of imagename.jpg?1421493843 and my
> images are broken?
>

Exactly, that's the issue! :)

**Comment by maxim** [comment]
Until we push the fix it's best to lock into paperclip no greater than 4.2.0.

**Comment by roymckenzie** [comment]
Thanks @maxim!
