### ISSUE TITLE
undefined method `[]=' for nil:NilClass when two images on one model

### ISSUE THREAD

**Issue by MarinaMartin** [jrgifford/delayed_paperclip#129]
I have two images in one model, and want to process both with delayed_paperclip. The upload of both works fine with Paperclip normally.

When I add "process_in_background" for the first item in the model, it works. When I add under the second item, I get: "undefined method `[]=' for nil:NilClass" and my entire application crashes until I comment out that line.

**Comment by m-k** [comment]
The issue with cached @paperclip_definitions. For now you should use process_in_background after all has_attached_file definitions.

**Comment by aug-riedinger** [comment]
For some reason, the issue is not found while googling the error message (which is the title of the issue here)... Any idea why?
Thanks anyway, it solved my problem!

**Comment by younes0** [comment]
yeah I had to comment all these lines to make it work 
```ruby
 process_in_background :logo
  process_in_background :wide_logo
  process_in_background :cover_photo
  process_in_background :small_cover_photo
  process_in_background :favicon
```

**Comment by aug-riedinger** [comment]
You don't need to comment them, simply put them **after** every `has_attached_file` definitions.

**Comment by younes0** [comment]
yup, I was just confirming that the issue was related to those instructions

**Comment by bipashant** [comment]
I'm also having the same issue.I tried all the solution above but didn't worked.

**Comment by digerata** [comment]
I've hit the same problem.  I have two attachments:

    has_attached_file :cover
    has_attached_file :avatar

If I put the process_in_background after my two has_attached_file definitions, it still fails.  Always on the second call.  So if has_attached_file :cover is declared first, :avatar will fail.  If :avatar is first, process_in_background(:cover) will fail. 

The location of process_in_background has no effect for me.  I'm using delayed_paperclip 2.9.1

Doing some debugging and it appears that the paperclip_definitions only ever has the first attachment as a key.  

Ideas?

**Comment by jasonivers** [comment]
I just started getting this today with v 3.0.0, after doing a bundle update.  I'm not certain what the cause is, but it completely broke calling .url on the attached file that was supposed to process in the background.  I moved things to ensure that process_in_background was called after both has_attached_file definitions and the methods I'm using for processing_image_url.  It had no effect.    This is version 3.0.0 of delayed_paperclip, and paperclip 5.1.0.  Version 5.0.0 of paperclip works fine.

**Comment by mskubenich** [comment]
This works for me https://github.com/mskubenich/delayed_paperclip/commit/37ac88432789914091ce32060ca7c6a5b62336f9

**Comment by NuckChorris** [comment]
@mskubenich That should get merged in and released, this is a major nuisance! :dancer:

**Comment by NuckChorris** [comment]
Beware!  It turns out that patch @mskubenich wrote will actually break delayed_paperclip.  All this debugging and it turns out @m-k had it right at the start — it was a memoization problem.

I wrote a patch which seems to successfully fix it and sent a PR, so hopefully that gets merged soon :)
