### ISSUE TITLE
What should happen if the original AR object is deleted before its bg job is started?

### ISSUE THREAD

**Issue by Jesus** [jrgifford/delayed_paperclip#144]
I think the current behavior involves raising an ActiveRecord::RecordNotFound from DelayedPaperclip.process_job when the job is trying to fetch the originating object.

But maybe the job should be deleted when its parent object is deleted?

**Comment by etagwerker** [comment]
@Jesus This issue is a duplicate of https://github.com/jrgifford/delayed_paperclip/issues/101

**Comment by Jesus** [comment]
I hadn't seen it, thanks.

Btw, thanks for your contribution!
