### ISSUE TITLE
Configure queue name

### ISSUE THREAD

**Issue by sgringwe** [jrgifford/delayed_paperclip#154]
How can I configure the name of the queue you use? Queues are expensive in sidekiq and I'd love to re-use another queue.

**Comment by ScotterC** [comment]
Here's where it gets set https://github.com/jrgifford/delayed_paperclip/blob/master/lib/delayed_paperclip/jobs/sidekiq.rb#L7

Would love it if you wanted to add a configuration option there

**Comment by morgoth** [comment]
Fixed in https://github.com/jrgifford/delayed_paperclip/pull/169
