### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thedrow** [jrgifford/delayed_paperclip#168]
There has been some fixes between the latest release and now.
Maybe it's time for a new 2.9.x release?

**Comment by ScotterC** [comment]
Yes @thedrow. It's a good idea. I've been busy but will hopefully get a release out next week.

**Comment by morgoth** [comment]
@ScotterC I think current master is a good candidate for a release - do you think it should be major or minor version? When to expect this release?

**Comment by ScotterC** [comment]
@morgoth agreed. I think we can keep this as a minor release because of how many bug fixes it takes care of. Working on it now

**Comment by morgoth** [comment]
Done in https://github.com/jrgifford/delayed_paperclip/pull/175
