### ISSUE TITLE
Improve maintenance of gem

### ISSUE THREAD

**Issue by morgoth** [jrgifford/delayed_paperclip#173]
Currently `delayed_paperclip` supports lot of background backends. It would be easier to maintain code if we could reduce it.

My idea is to move forward and go altogether with paperclip 5.0 (which currently is in beta) and drop support for Rails < 4.2 and Ruby 2.0 https://github.com/thoughtbot/paperclip/blob/f7aa32069cc798dc96ca07c8dceee2ced7a1b571/NEWS#L5-L6

Rails 4.2 introduced ActiveJob, so what do you think about dropping support for other backends and use only AJ?

**Comment by ScotterC** [comment]
@morgoth I think we should do this with a major version change

**Comment by morgoth** [comment]
Yes, sure - with some deprecation warning in minor release.
Altogether with https://github.com/jrgifford/delayed_paperclip/pull/169 what should be the next release? Major or just minor?

**Comment by morgoth** [comment]
ongoing on https://github.com/jrgifford/delayed_paperclip/pull/178
