### ISSUE TITLE
Latest commit to paperclip master breaks gem

### ISSUE THREAD

**Issue by jeffblake** [jrgifford/delayed_paperclip#191]
![screen shot 2016-08-16 at 8 26 43 pm](https://cloud.githubusercontent.com/assets/620564/17723570/dd6908f2-63ef-11e6-98e2-6ca86aa94a3f.png)
![screen shot 2016-08-16 at 8 26 53 pm](https://cloud.githubusercontent.com/assets/620564/17723571/dff4b53a-63ef-11e6-8558-8977c6826e09.png)

https://github.com/thoughtbot/paperclip/commit/09d6bb7865c06de9e4b90328f507977ae6146814

**Comment by morgoth** [comment]
@jeffblake Thanks. This should be now fixed on master
