### ISSUE TITLE
undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by jasonivers** [jrgifford/delayed_paperclip#193]
There is an open issue that mentions this (https://github.com/jrgifford/delayed_paperclip/issues/129), but the remedies mentioned in that solution did not work for me, and this appears to be related to Paperclip v 5.1.0.  Paperclip v 5.0.0 and DelayedPaperclip v 3.0.0 work fine together.  Paperclip v 5.1.0 and DelayedPaperclip v 3.0.0 cause this error to occur whenever trying to reference model.attachment.url (model.attachment works fine).

I apologize, but I don't have time to spend debugging this, currently.

**Comment by morgoth** [comment]
@jasonivers This should be fixed in 3.0.1 which is now released - can you please try it and confirm?

**Comment by jasonivers** [comment]
Yes, that seems to have done it.  Thank you for the prompt attention.
