### ISSUE TITLE
expiring_url does not work with "Displaying images during processing"

### ISSUE THREAD

**Issue by chapter9** [jrgifford/delayed_paperclip#36]
Hi

I'm using Delayed_Paperclip with S3 and using the following function to display my images:  http://rubydoc.info/github/thoughtbot/paperclip/Paperclip/Storage/S3:expiring_url

The problem is that it does not work according to your section "Displaying images during processing".

Here's my current workaround:

``` ruby
<%= image_tag image_link.image.expiring_url(3600, image_link.image.processing? ? :original : :square) %>
```

It would be better delayed_paperclip could override this function to return the proper default_image

**Comment by viseztrance** [comment]
I'm having the same issue. The expiring_url method always returns the computed s3 expiring path, not the processing image.
