### ISSUE TITLE
Add simple queue support for delayed_job

### ISSUE THREAD

**Issue by KieranBroadfoot** [jrgifford/delayed_paperclip#41]
I would like to suggest the inclusion of queuing semantics into jobs/delayed_job.rb for those who use the latest versions of DJ.  Happy to send a very simple pull request if you would be interested.

This enables me (and anyone else who would benefit) to distinctly manage delayed paperclip tasks without needing to ensure all other tasks are kept off the main queue.

Thanks
k.

**Comment by noctivityinc** [comment]
+1

**Comment by morgoth** [comment]
Looks like it's fixed in https://github.com/jrgifford/delayed_paperclip/pull/169
